package biodata;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aleq
 */
public class Biodata extends javax.swing.JFrame {

    int baris;
    UserTableModel mahasiswa;

    /**
     * Creates new form biodata_aleq
     */
    public Biodata() {
        initComponents();

        kirim.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        batal.setEnabled(false);

        nim.setEnabled(false);
        nama.setEnabled(false);
        fakultas.setEnabled(false);
        prodi.setEnabled(false);
        angkatan.setEnabled(false);

        baris = tabelBiodata.getSelectedRow();
        tabelBiodata.addMouseListener(new tabelListener());

        System.out.println(baris);

        if (baris >= 0) {
            ubah.setEnabled(true);
            hapus.setEnabled(true);
        }
        String header[] = {"NIM", "Nama", "fakultas", "Program Studi", "Angkatan"};
        mahasiswa = new UserTableModel(null, header);
        updateTabel();
    }

    private void updateTabel() {
        tabelBiodata.setModel(mahasiswa);
    }

    private boolean tambahData(String nim, String nama, String fakultas, String prodi, String angkatan) {
        String dataPerBaris[] = new String[]{
            nim, nama, fakultas, prodi, angkatan
        };
        mahasiswa.addRow(dataPerBaris);
        return true;
    }

    private boolean ubahData(String nim, String nama, String fakultas, String prodi, String angkatan, int baris) {
        mahasiswa.setValueAt(nim, baris, 0);
        mahasiswa.setValueAt(nama, baris, 1);
        mahasiswa.setValueAt(fakultas, baris, 2);
        mahasiswa.setValueAt(prodi, baris, 3);
        mahasiswa.setValueAt(angkatan, baris, 4);
        return true;
    }

    private boolean hapusData(int baris) {
        mahasiswa.removeRow(baris);
        return true;
    }

    private class tabelListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            baris = tabelBiodata.getSelectedRow();

            ubah.setEnabled(true);
            hapus.setEnabled(true);

            nim.setEnabled(true);
            nama.setEnabled(true);
            fakultas.setEnabled(true);
            prodi.setEnabled(true);
            angkatan.setEnabled(true);

            nim.setText(tabelBiodata.getValueAt(baris, 0).toString());
            nama.setText(tabelBiodata.getValueAt(baris, 1).toString());
            fakultas.setText(tabelBiodata.getValueAt(baris, 2).toString());
            prodi.setText(tabelBiodata.getValueAt(baris, 3).toString());
            angkatan.setText(tabelBiodata.getValueAt(baris, 4).toString());
        }

        //<editor-fold defaultstate="collapsed" desc="useless">
        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        fakultas = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kirim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBiodata = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        prodi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        angkatan = new javax.swing.JTextField();
        batal = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Fakultas");

        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });

        fakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakultasActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        kirim.setText("Selesai");
        kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimActionPerformed(evt);
            }
        });

        tabelBiodata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Fakultas", "Prodi", "Angkatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBiodata.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelBiodata);

        jLabel5.setText("Prodi");

        jLabel6.setText("Angkatan");

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kirim)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(batal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(ubah)
                    .addComponent(hapus)
                    .addComponent(kirim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        nim.setText("");
        nama.setText("");
        fakultas.setText("");
        prodi.setText("");
        angkatan.setText("");

        tambah.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        kirim.setEnabled(true);
        batal.setEnabled(true);

        nim.setEnabled(true);
        nama.setEnabled(true);
        fakultas.setEnabled(true);
        prodi.setEnabled(true);
        angkatan.setEnabled(true);
    }//GEN-LAST:event_tambahActionPerformed

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
    }//GEN-LAST:event_nimActionPerformed

    private void kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimActionPerformed
        String sNim = nim.getText();
        String sNama = nama.getText();
        String sFakultas = fakultas.getText();
        String sProdi = prodi.getText();
        String sAngkatan = angkatan.getText();

        boolean statusData = true;

        if (sNim.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "NIM Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sNama.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Nama Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sFakultas.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Fakultas Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sProdi.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Prodi Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sAngkatan.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Angkatan Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }

        if (statusData) {
            tambahData(sNim, sNama, sFakultas, sProdi, sAngkatan);
            nim.setText("");
            nama.setText("");
            fakultas.setText("");
            prodi.setText("");
            angkatan.setText("");

            tambah.setEnabled(true);
            kirim.setEnabled(false);
            ubah.setEnabled(false);
            hapus.setEnabled(false);
            batal.setEnabled(false);

            nim.setEnabled(false);
            nama.setEnabled(false);
            fakultas.setEnabled(false);
            prodi.setEnabled(false);
            angkatan.setEnabled(false);
        }
        updateTabel();
    }//GEN-LAST:event_kirimActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        String sNim = nama.getText();
        String sNama = nim.getText();
        String sFakultas = fakultas.getText();
        String sProdi = prodi.getText();
        String sAngkatan = angkatan.getText();

        boolean statusData = true;

        if (sNim.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "NIM Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sNama.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Nama Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sFakultas.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Fakultas Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sProdi.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Prodi Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }
        if (sAngkatan.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Angkatan Harus Diisi", "Perhatian", JOptionPane.WARNING_MESSAGE);
            statusData = false;
        }

        if (statusData) {
            ubahData(sNim, sNama, sFakultas, sProdi, sAngkatan, baris);
            nim.setText("");
            nama.setText("");
            fakultas.setText("");
            prodi.setText("");
            angkatan.setText("");

            tambah.setEnabled(true);
            kirim.setEnabled(false);
            ubah.setEnabled(false);
            hapus.setEnabled(false);
            batal.setEnabled(false);

            nim.setEnabled(false);
            nama.setEnabled(false);
            fakultas.setEnabled(false);
            prodi.setEnabled(false);
            angkatan.setEnabled(false);
        }
        updateTabel();
    }//GEN-LAST:event_ubahActionPerformed

    private void fakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fakultasActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        nim.setText("");
        nama.setText("");
        fakultas.setText("");
        prodi.setText("");
        angkatan.setText("");

        tambah.setEnabled(true);
        kirim.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        batal.setEnabled(false);

        nim.setEnabled(false);
        nama.setEnabled(false);
        fakultas.setEnabled(false);
        prodi.setEnabled(false);
        angkatan.setEnabled(false);
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        hapusData(baris);
        kirim.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        batal.setEnabled(false);

        nim.setEnabled(false);
        nama.setEnabled(false);
        fakultas.setEnabled(false);
        prodi.setEnabled(false);
        angkatan.setEnabled(false);

        nim.setText("");
        nama.setText("");
        fakultas.setText("");
        prodi.setText("");
        angkatan.setText("");
        updateTabel();
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biodata().setVisible(true);
            }
        });
    }
    //<editor-fold defaultstate="collapsed" desc="variable declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkatan;
    private javax.swing.JButton batal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField fakultas;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kirim;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField prodi;
    private javax.swing.JTable tabelBiodata;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
